language: python
sudo: true
dist: xenial  # Required for 3.7 as of 2018/12
python:
- '3.7'
- '3.6'
install:
- sudo apt-get update
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda;
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy scikit-learn pytest
  coverage
- source activate test-environment
- pip install coveralls nose
- python -m pip install .
script:
- pytest .
- coverage
- coverage combine # required for multiprocessing
after_success:
- coveralls
cache:
- apt
- directories:
  - "$HOME/.cache/pip"
